"""Add deleted_at to User

Revision ID: 1b959ad90b7d
Revises: 3488f4c5bf36
Create Date: 2025-10-29 12:53:42.969136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b959ad90b7d'
down_revision: Union[str, Sequence[str], None] = '3488f4c5bf36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('posts', 'is_deleted')
    op.add_column('tags', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('tags', 'is_deleted')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'deleted_at')
    op.add_column('tags', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tags', 'deleted_at')
    op.add_column('posts', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'deleted_at')
    # ### end Alembic commands ###
